### ISSUE TITLE
RuntimeError: "CRF.py", line 94, in _compute_likelihood_denominator

### ISSUE THREAD

**Issue by jjkislele** [freddyalfonsoboulton/crf_tutorial#2]
Sorry for missing the first issue from Shaunlipy. 

>  I used torch 0.3.0 for this post so maybe torch 0.4 is causing the issue?

Yes, it is. Also, in ``utils.py`` line 24, ``ll`` is a zero-dimensional tensor. We should use ``ll.data.numpy()`` instead of  ``ll.data.numpy()[0]``. 

-----------------------------------------------------

```
93        alpha_t.append(self.log_sum_exp(alpha_t_next_state))
94    prev_alpha = torch.cat(alpha_t).view(1, -1)
```

When I run ``crf_demo.ipynb`` you provide, exactly in ``model = crf_train_loop(model, rolls, targets, 1, 0.001)``, I meet the error as below:

```
File "crf_tutorial-master/CRF.py", line 94, in _compute_likelihood_denominator
   prev_alpha = torch.cat(alpha_t).view(1, -1)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
```

Obviously, ``alpha_t[0]`` is a zero-dimensional tensor, and ``alpha_t`` is a list. ``alpha_t[0]`` should use ``.view(1, -1)`` or some other methods to trans into the 2-dimensional tensor. That's to say, ``alpha_t[0].shape()`` should be ``torch.Size([1, 1])``.

So, maybe in line 93, the code should be modified as:

```
93        alpha_t.append(self.log_sum_exp(alpha_t_next_state).view(1, -1))
```

Thanks.

**Comment by ShilazTech** [comment]
Yes. I tried and above suggestion works
